% バイアスの適用
real_cmd_vel = [cmd_vel(1)*bias_rate_nu, ...
                cmd_vel(2)*bias_rate_omega]; 
% 実ロボットの位置を計算
pose = common.cmd_vel_to_pose(real_cmd_vel(1), ...
                       real_cmd_vel(2), ...
                       sampling_time, pose);
% 外乱（小石を踏んだこと）による向きに対しての雑音
distance_until_noise = distance_until_noise ...
                       - (abs(real_cmd_vel(1)*sampling_time)...
                       +r*abs(real_cmd_vel(2))*sampling_time);
if distance_until_noise <=0.0
    distance_until_noise = distance_until_noise ...
                           + exprnd(1.0/(1e-100+noise_per_meter));
    pose(3) = pose(3) + normrnd(0, noise_std, 1);
end
clear theta_tmp real_cmd_vel
