for i=1:length(particles)
    sigmas = mvnrnd([0, 0, 0, 0], motion_Sigma);
    noised_nu = cmd_vel(1) ...
                + sigmas(1)*sqrt(abs(cmd_vel(1)/sampling_time))...
                + sigmas(2)*sqrt(abs(cmd_vel(2)/sampling_time));
    noised_omega = cmd_vel(2) ...
                + sigmas(3)*sqrt(abs(cmd_vel(1)/sampling_time))...
                + sigmas(4)*sqrt(abs(cmd_vel(2)/sampling_time));
    pose_tmp = particles(i, 1:3);
    particles(i, 1:3) = common.cmd_vel_to_pose(noised_nu, ...
                                               noised_omega, ...
                                               sampling_time, ...
                                               pose_tmp);
end
clear sigmas noised_nu noised_omega pose_tmp